spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/crypto-tracker
  security:
    user:
      name: user
      password: password
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
kafka:
  bootstrap-servers: localhost:9092
